### ISSUE TITLE
Fortran Equivalent

### ISSUE THREAD

**Issue by matsupe** [WISDEM/pBEAM#2]
Is there a Fortran equivalent of pBEAM or any other 3D beam model for turbine blades available for academic purposes (i.e. free)? You mention it's based on the book by Yang 1986, but doesn't that book already include Fortran code at the back? I want to implement pBEAM on a cluster, but all the prerequisites make it difficult to do so. I want to combine pBEAM with PreComp into a single executable.

I'm trying to get a copy of that book, but it's old and I can't download it from the internet.

**Comment by andrewning** [comment]
There is a freely available C code, [Frame3DD](http://frame3dd.sourceforge.net) that we've used for other things.  Integrating C and Fortran is not too bad.

There is some code in the back of Yang, but I don't know to what level of depth.  I suspect you'd still need to integrate several pieces to make it work.
