### ISSUE TITLE
NameError: name 'CalledProcessError' is not defined

### ISSUE THREAD

**Issue by Gurren-Joestar** [WISDEM/pBEAM#3]
I tried to install through anaconda 3 when suddenly it said:

running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "_pBEAM" sources
build_src: building npy-pkg config files
writing pBEAM.egg-info\PKG-INFO
writing dependency_links to pBEAM.egg-info\dependency_links.txt
writing top-level names to pBEAM.egg-info\top_level.txt
reading manifest file 'pBEAM.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'docs\_build\html'
writing manifest file 'pBEAM.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 75, in __init__
    out_string  = subprocess.check_output(['gcc', '-dumpversion'])
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    setup(
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\core.py", line 171, in setup
    return old_setup(**new_attr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\command\install.py", line 62, in run
    r = self.setuptools_run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\command\install.py", line 56, in setuptools_run
    self.do_egg_install()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\command\build_ext.py", line 121, in run
    self.compiler = new_compiler(compiler=compiler_type,
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\ccompiler.py", line 771, in new_compiler
    compiler = klass(None, dry_run, force)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 76, in __init__
    **except (OSError, CalledProcessError):**
**NameError: name 'CalledProcessError' is not defined**

**Comment by Gurren-Joestar** [comment]
![image](https://user-images.githubusercontent.com/71229258/97216396-c3f24d00-1793-11eb-9e27-3588264ecaad.png)

**Comment by Gurren-Joestar** [comment]
![image](https://user-images.githubusercontent.com/71229258/97217208-e9cc2180-1794-11eb-872d-9144ad30d68d.png)

**Comment by gbarter** [comment]
Hello,

It looks like you are mixing Cygwin compilers with Anaconda packages, which I would strongly advise against.  In a fresh conda environment, pBeam should compile without issue using the `compilers` and `libpython` packages on Windows.  If you are using Cygwin, then do not use Anaconda but instead just the Cygwin python packages and standard GNU `gcc` packages.

Finally, it also looks like you are trying to call pBeam with a subprocess call from python, which is unnecessary.  Instead please follow the example [here](https://wisdem.github.io/pBEAM/tutorial.html).

Cheers,
Garrett

**Comment by gbarter** [comment]
Finally, I would note that if you are attempting to use pBeam as a standalone, that is fine.  WISDEM will be moving away from pBeam in the next official release (December of January) and use Frame3DD exclusively instead.

**Comment by Gurren-Joestar** [comment]
Greetings
Before i published this issue i was having trouble with c++ 

> _compiling C sources
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/_

So i installed some similar package from anaconda 

> _pybind11                  2.5.0            py38h74a9793_0_

And also I installed libpython (which contains mingw) from anaconda 

> _libpython                 2.1                      py38_0_

I installed libpython because of (from Git-Hub: https://github.com/WISDEM/pBEAM)

> Prerequisites
> C++ compiler (with c++11 support), NumPy
> 
> Note that any modern compiler (gcc, clang, etc) on Linux or MacOS will support the c++11 standard. **On Windows, recommend to use mingw through Anaconda** or gcc on Cygwin.

After receiving your reply i create a new environment then i installed one by one and finally i realized :

- pybind11 doesnt help to compile c++
- libpython was the problem of the issue 

I guess i need to install Microsoft Visual C++ 14.0 from outside conda enviroment (Visual Studio Build Tools), it weight like 4 GB. 

Im not sure if conda would recognize it.
Do you think i should install Microsoft Visual C++ from Visual Studio?

**Comment by gbarter** [comment]
No.  We have had many problems with MS Visual Studio playing nicely with Anaconda.  I realize also I said to install the `compilers` package- that was a mistake on my part as that only exists for Linux and Mac.  On Windows, the Anaconda package you need is `m2w64-toolchain `.  This will give you all of the compilers.

**Comment by Gurren-Joestar** [comment]
Now I installed **`m2w64-toolchain`** , 

> `C:\WINDOWS\system32>conda install -c conda-forge m2w64-toolchain_win-64`

**`libpython`** 

> `C:\WINDOWS\system32>conda install libpython`

and **`numpy`** on my conda enviroment (python 3.6)
 
> `C:\WINDOWS\system32>conda install numpy`

and when i run `C:\Users\User\Documents\GitHub\pBEAM>python setup.py install `, i got this:


running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "_pBEAM" sources
build_src: building npy-pkg config files
writing pBEAM.egg-info\PKG-INFO
writing dependency_links to pBEAM.egg-info\dependency_links.txt
writing top-level names to pBEAM.egg-info\top_level.txt
reading manifest file 'pBEAM.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'docs\_build\html'
writing manifest file 'pBEAM.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
customize Mingw32CCompiler
customize Mingw32CCompiler using build_ext
customize Mingw32CCompiler
customize Mingw32CCompiler using build_ext
building '_pBEAM' extension
compiling C++ sources
C compiler: g++ -g -DDEBUG -DMS_WIN64 -O0 -Wall

creating build\temp.win-amd64-3.6\Release\src
creating build\temp.win-amd64-3.6\Release\src\pbeam
creating build\temp.win-amd64-3.6\Release\src\pybeam
compile options: '-D__MSVCRT_VERSION__=0x1916 -Isrc\pBEAM -Isrc\include -IC:\Users\User\.conda\envs\Trial\lib\site-packages\numpy\core\include -IC:\Users\User\.conda\envs\Trial\include -IC:\Users\User\.conda\envs\Trial\include -c'
extra options: '-std=gnu++11 -fPIC'
g++ -g -DDEBUG -DMS_WIN64 -O0 -Wall -D__MSVCRT_VERSION__=0x1916 -Isrc\pBEAM -Isrc\include -IC:\Users\User\.conda\envs\Trial\lib\site-packages\numpy\core\include -IC:\Users\User\.conda\envs\Trial\include -IC:\Users\User\.conda\envs\Trial\include -c src\pBEAM\BeamFEA.cpp -o build\temp.win-amd64-3.6\Release\src\pbeam\beamfea.o -std=gnu++11 -fPIC
g++ -g -DDEBUG -DMS_WIN64 -O0 -Wall -D__MSVCRT_VERSION__=0x1916 -Isrc\pBEAM -Isrc\include -IC:\Users\User\.conda\envs\Trial\lib\site-packages\numpy\core\include -IC:\Users\User\.conda\envs\Trial\include -IC:\Users\User\.conda\envs\Trial\include -c src\pBEAM\Poly.cpp -o build\temp.win-amd64-3.6\Release\src\pbeam\poly.o -std=gnu++11 -fPIC
g++ -g -DDEBUG -DMS_WIN64 -O0 -Wall -D__MSVCRT_VERSION__=0x1916 -Isrc\pBEAM -Isrc\include -IC:\Users\User\.conda\envs\Trial\lib\site-packages\numpy\core\include -IC:\Users\User\.conda\envs\Trial\include -IC:\Users\User\.conda\envs\Trial\include -c src\pBEAM\CurveFEM.cpp -o build\temp.win-amd64-3.6\Release\src\pbeam\curvefem.o -std=gnu++11 -fPIC
g++ -g -DDEBUG -DMS_WIN64 -O0 -Wall -D__MSVCRT_VERSION__=0x1916 -Isrc\pBEAM -Isrc\include -IC:\Users\User\.conda\envs\Trial\lib\site-packages\numpy\core\include -IC:\Users\User\.conda\envs\Trial\include -IC:\Users\User\.conda\envs\Trial\include -c src\pBEAM\myMath.cpp -o build\temp.win-amd64-3.6\Release\src\pbeam\mymath.o -std=gnu++11 -fPIC
src\pBEAM\myMath.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 //
 ^
src\pBEAM\BeamFEA.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 //
 ^
src\pBEAM\Poly.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 //
 ^
src\pBEAM\CurveFEM.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 //
 ^
g++ -g -DDEBUG -DMS_WIN64 -O0 -Wall -D__MSVCRT_VERSION__=0x1916 -Isrc\pBEAM -Isrc\include -IC:\Users\User\.conda\envs\Trial\lib\site-packages\numpy\core\include -IC:\Users\User\.conda\envs\Trial\include -IC:\Users\User\.conda\envs\Trial\include -c src\pBEAM\Beam.cpp -o build\temp.win-amd64-3.6\Release\src\pbeam\beam.o -std=gnu++11 -fPIC
g++ -g -DDEBUG -DMS_WIN64 -O0 -Wall -D__MSVCRT_VERSION__=0x1916 -Isrc\pBEAM -Isrc\include -IC:\Users\User\.conda\envs\Trial\lib\site-packages\numpy\core\include -IC:\Users\User\.conda\envs\Trial\include -IC:\Users\User\.conda\envs\Trial\include -c src\pyBEAM\pyBEAM.cpp -o build\temp.win-amd64-3.6\Release\src\pybeam\pybeam.o -std=gnu++11 -fPIC
src\pBEAM\Beam.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 //
 ^
src\pyBEAM\pyBEAM.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 //
 ^
In file included from src\pBEAM\Beam.cpp:14:0:
src\pBEAM\Beam.h: In constructor 'Beam::Beam(const PolynomialSectionData&, const PolynomialLoads&, const TipData&, const BaseData&)':
src\pBEAM\Beam.h:43:12: warning: 'Beam::z_node' will be initialized after [-Wreorder]
     Vector z_node;
            ^
src\pBEAM\Beam.h:39:13: warning:   'PolyVec Beam::Px' [-Wreorder]
     PolyVec Px;
             ^
src\pBEAM\Beam.cpp:138:1: warning:   when initialized here [-Wreorder]
 Beam::Beam(const PolynomialSectionData& sec, const PolynomialLoads& loads,
 ^
creating build\lib.win-amd64-3.6
g++ -g -shared build\temp.win-amd64-3.6\Release\src\pbeam\poly.o build\temp.win-amd64-3.6\Release\src\pbeam\mymath.o build\temp.win-amd64-3.6\Release\src\pbeam\beamfea.o build\temp.win-amd64-3.6\Release\src\pbeam\curvefem.o build\temp.win-amd64-3.6\Release\src\pbeam\beam.o build\temp.win-amd64-3.6\Release\src\pybeam\pybeam.o -LC:\Users\User\.conda\envs\Trial\libs -LC:\Users\User\.conda\envs\Trial\PCbuild\amd64 -lpython36 -o build\lib.win-amd64-3.6\_pBEAM.cp36-win_amd64.pyd
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib/libmingw32.a when searching for -lmingw32
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib\libmingw32.a when searching for -lmingw32
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib/libmoldname.a when searching for -lmoldname
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib\libmoldname.a when searching for -lmoldname
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib/libmingwex.a when searching for -lmingwex
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib\libmingwex.a when searching for -lmingwex
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib/libmsvcrt.a when searching for -lmsvcrt
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib\libmsvcrt.a when searching for -lmsvcrt
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib/libadvapi32.a when searching for -ladvapi32
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib\libadvapi32.a when searching for -ladvapi32
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib/libshell32.a when searching for -lshell32
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib\libshell32.a when searching for -lshell32
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib/libuser32.a when searching for -luser32
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib\libuser32.a when searching for -luser32
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib/libkernel32.a when searching for -lkernel32
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib\libkernel32.a when searching for -lkernel32
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib/libmingw32.a when searching for -lmingw32
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib\libmingw32.a when searching for -lmingw32
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib/libmoldname.a when searching for -lmoldname
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib\libmoldname.a when searching for -lmoldname
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib/libmingwex.a when searching for -lmingwex
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib\libmingwex.a when searching for -lmingwex
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib/libmsvcrt.a when searching for -lmsvcrt
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/G95/lib/../lib\libmsvcrt.a when searching for -lmsvcrt
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:/Program Files (x86)/G95/lib/../lib/dllcrt2.o' is incompatible with i386:x86-64 output
C:/Users/User/.conda/envs/Trial/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: cannot find entry symbol DllMainCRTStartup; defaulting to 0000000061681000
C:/Program Files (x86)/G95/lib/../lib/dllcrt2.o:dllcrt1.c:(.text+0x44): undefined reference to `_free'
C:/Program Files (x86)/G95/lib/../lib/dllcrt2.o:dllcrt1.c:(.text+0x58): undefined reference to `_fflush'
C:/Program Files (x86)/G95/lib/../lib/dllcrt2.o:dllcrt1.c:(.text+0x82): undefined reference to `_DllMain@12'
C:/Program Files (x86)/G95/lib/../lib/dllcrt2.o:dllcrt1.c:(.text+0xbf): undefined reference to `_malloc'
C:/Program Files (x86)/G95/lib/../lib/dllcrt2.o:dllcrt1.c:(.text+0xd8): undefined reference to `__pei386_runtime_relocator'
C:/Program Files (x86)/G95/lib/../lib/dllcrt2.o:dllcrt1.c:(.text+0xdd): undefined reference to `___main'
C:/Program Files (x86)/G95/lib/../lib/dllcrt2.o:dllcrt1.c:(.text+0xf8): undefined reference to `__errno'
C:/Program Files (x86)/G95/lib/../lib/dllcrt2.o:dllcrt1.c:(.text+0x12f): undefined reference to `___dllonexit'
C:/Program Files (x86)/G95/lib/../lib/dllcrt2.o:dllcrt1.c:(.text+0x15f): undefined reference to `___dllonexit'
ertr000001.o:(.rdata+0x0): undefined reference to `_pei386_runtime_relocator'
collect2.exe: error: ld returned 1 exit status
**error:** Command "g++ -g -shared build\temp.win-amd64-3.6\Release\src\pbeam\poly.o build\temp.win-amd64-3.6\Release\src\pbeam\mymath.o build\temp.win-amd64-3.6\Release\src\pbeam\beamfea.o build\temp.win-amd64-3.6\Release\src\pbeam\curvefem.o build\temp.win-amd64-3.6\Release\src\pbeam\beam.o build\temp.win-amd64-3.6\Release\src\pybeam\pybeam.o -LC:\Users\User\.conda\envs\Trial\libs -LC:\Users\User\.conda\envs\Trial\PCbuild\amd64 -lpython36 -o build\lib.win-amd64-3.6\_pBEAM.cp36-win_amd64.pyd" failed with exit status 1


Mingw32 is from numpy package, if i uninstall it from conda, it wont let me install PBeam
Without libpython, conda will suggest me to use C++14 from VS
Without m2w64-toolchain, i will be on my inicial issue

**Comment by Gurren-Joestar** [comment]
Those are my conda packages:

(Trial) C:\Users\User\Documents\GitHub\pBEAM>conda list
# packages in environment at C:\Users\User\.conda\envs\Trial:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
certifi                   2020.6.20                py36_0
intel-openmp              2020.2                      254
libpython                 2.1                      py36_0
m2w64-binutils            2.25.1                        5
m2w64-bzip2               1.0.6                         6
m2w64-crt-git             5.0.0.4636.2595836               2
m2w64-gcc                 5.3.0                         6
m2w64-gcc-ada             5.3.0                         6
m2w64-gcc-fortran         5.3.0                         6
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gcc-objc            5.3.0                         6
m2w64-gmp                 6.1.0                         2
m2w64-headers-git         5.0.0.4636.c0ad18a               2
m2w64-isl                 0.16.1                        2
m2w64-libiconv            1.14                          6
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-make                4.1.2351.a80a8b8               2
m2w64-mpc                 1.0.3                         3
m2w64-mpfr                3.1.4                         4
m2w64-pkg-config          0.29.1                        2
m2w64-toolchain           5.3.0                         7
m2w64-toolchain_win-64    2.4.0                         0    conda-forge
m2w64-tools-git           5.0.0.4592.90b8472               2
m2w64-windows-default-manifest 6.4                           3
m2w64-winpthreads-git     5.0.0.4634.697f757               2
m2w64-zlib                1.2.8                        10
mkl                       2020.2                      256
mkl-service               2.3.0            py36hb782905_0
mkl_fft                   1.2.0            py36h45dec08_0
mkl_random                1.1.1            py36h47e9c7a_0
msys2-conda-epoch         20160418                      1
numpy                     1.19.2           py36hadc3359_0
numpy-base                1.19.2           py36ha3acd2a_0
pip                       20.2.4                   py36_0
python                    3.6.12               h5500b2f_2
setuptools                50.3.0           py36h9490d1a_1
six                       1.15.0                     py_0
sqlite                    3.33.0               h2a8f88b_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wheel                     0.35.1                     py_0
wincertstore              0.2              py36h7fe50ca_0
zlib                      1.2.11               h62dcd97_4

**Comment by gbarter** [comment]
This isn't a problem with your conda packages or numpy.  It looks like you have a 32-bit MinGW installation at C:/Program Files (x86)/G95/ that is super-ceding the Anaconda version when the compiler is looking for libraries.  You might move that away temporarily or you will have to hard-code some edits to the compiler directives in the setup.py script, but I would have a hard time offering help with that approach as I cannot replicate your problem.  If you do something to fix the issue, be sure to fully delete the build-directory in pBeam as you will need to recompile everything again.

**Comment by Gurren-Joestar** [comment]
Thanks, i delete the variable enviroment (in windows) for g95 and move away their files from program data and then it works:

Processing pBEAM-0.2.0-py3.6-win-amd64.egg
creating c:\users\user\.conda\envs\trial\lib\site-packages\pBEAM-0.2.0-py3.6-win-amd64.egg
Extracting pBEAM-0.2.0-py3.6-win-amd64.egg to c:\users\user\.conda\envs\trial\lib\site-packages
Adding pBEAM 0.2.0 to easy-install.pth file

Installed c:\users\user\.conda\envs\trial\lib\site-packages\pbeam-0.2.0-py3.6-win-amd64.egg
Processing dependencies for pBEAM==0.2.0
Finished processing dependencies for pBEAM==0.2.0

**Comment by Gurren-Joestar** [comment]
![image](https://user-images.githubusercontent.com/71229258/97334805-23f7fa80-184b-11eb-8b61-45c96cbd8562.png)
